In [1]:
import pandas as pd
from pathlib import Path

# Column Manipulation

In [2]:
csvpath = Path("../Resources/customers.csv")

In [3]:
customer_dataframe = pd.read_csv(csvpath)
customer_dataframe.head()

,FullName,Email,Address,Zip,CreditCard,Balance
0,Altha Frederick,unhideable1966@gmail.com,67 John Maher Extension,31353,2524 2317 2139 4751,21511
1,Nickolas Harvey,allgood1803@outlook.com,1200 Madera Plaza,1922,4756 0997 9568 1329,13850
2,Jesusita Kinney,satsumas1954@yahoo.com,943 Gibb Highway,41535,3717 863466 48574,21254
3,Mose Gordon,antifowl1875@gmail.com,1073 Fell Trace,16098,5413 1700 6989 2835,5221
4,Cesar Valentine,acetaminol1979@yahoo.com,805 Marshall Promenade,99895,5173 4883 9215 4743,8300

In [4]:
customer_dataframe.columns

Index(['FullName', 'Email', 'Address', 'Zip', 'CreditCard', 'Balance'], dtype='object')

In [7]:
customer_dataframe["Email"]

0          unhideable1966@gmail.com
1           allgood1803@outlook.com
2            satsumas1954@yahoo.com
3            antifowl1875@gmail.com
4          acetaminol1979@yahoo.com
5          commanding1927@gmail.com
6              breeds1855@gmail.com
7           pronounal1891@yahoo.com
8        blacklegging1855@yahoo.com
9           octachord1995@yahoo.com
10          clarified1907@gmail.com
11           pachytene1885@live.com
12              barb2038@yandex.com
13            double2010@yandex.com
14      occidentalism1859@yahoo.com
15          siamese1936@outlook.com
16        nonswimming1985@yahoo.com
17          dockyards2058@yahoo.com
18            paucity1995@yahoo.com
19            pouncing1910@live.com
20                heft1945@live.com
21          charmian1906@yandex.com
22             curate1853@gmail.com
23         concentrate1983@live.com
24     exceptionalness2044@live.com
25               bijou1921@live.com
26               euda1886@yahoo.com
27        batteries2003@outlook.com
28           shivarees1849@live.com
29        cappadine1872@outlook.com
                  ...
70            mayfly1903@yandex.com
71           beylic1844@outlook.com
72            finch2041@outlook.com
73             annoyed2054@live.com
74         apolline1844@outlook.com
75             ashton1830@gmail.com
76             dovelet1813@live.com
77             rivals1832@gmail.com
78            porpoise1827@live.com
79        nonanarchic2041@gmail.com
80    consciousness1931@outlook.com
81         byproducts1960@yahoo.com
82             amines1975@gmail.com
83            cousins1924@gmail.com
84            poephaga1853@live.com
85              eller1996@gmail.com
86             peddles2025@live.com
87          posadaship2026@live.com
88             exciton1867@live.com
89              detur2023@yahoo.com
90        untightened1949@gmail.com
91         concrete1909@outlook.com
92        demandative1829@yahoo.com
93              arlin2068@gmail.com
94          malarkeys1970@yahoo.com
95            plantula1818@live.com
96         doolittle1818@yandex.com
97               mosso1961@live.com
98           ovenful1914@yandex.com
99             esson1909@yandex.com
Name: Email, Length: 100, dtype: object

In [13]:
customer_dataframe = customer_dataframe.rename(columns={
    "FullName":"full_name",
    "Zip":"zip_code"
})

In [14]:
customer_dataframe

,full_name,Email,Address,zip_code,CreditCard,Balance
0,Altha Frederick,unhideable1966@gmail.com,67 John Maher Extension,31353,2524 2317 2139 4751,21511
1,Nickolas Harvey,allgood1803@outlook.com,1200 Madera Plaza,1922,4756 0997 9568 1329,13850
2,Jesusita Kinney,satsumas1954@yahoo.com,943 Gibb Highway,41535,3717 863466 48574,21254
3,Mose Gordon,antifowl1875@gmail.com,1073 Fell Trace,16098,5413 1700 6989 2835,5221
4,Cesar Valentine,acetaminol1979@yahoo.com,805 Marshall Promenade,99895,5173 4883 9215 4743,8300
5,Erich Wooten,commanding1927@gmail.com,239 Mckinley Line,13494,2409 0669 5036 3311,6863
6,Elias Ayers,breeds1855@gmail.com,1109 Teresita Point,41281,3469 558618 10693,17492
7,Boris Macdonald,pronounal1891@yahoo.com,641 Lexington Run,92696,3723 385818 86151,24022
8,Emilio Bird,blacklegging1855@yahoo.com,222 Moulton Brae,70027,2290 4873 9990 0632,23237
9,Vincenza Patel,octachord1995@yahoo.com,1245 Whiting Parkway,30788,3736 301018 61659,7716
10,Norberto Pollard,clarified1907@gmail.com,1362 Fulton Trace,73193,4194 4559 1314 2000,7392
11,Kristeen Hutchinson,pachytene1885@live.com,347 Deming Thruway,97440,4699 9501 3316 8645,2807
12,Jestine Mcdowell,barb2038@yandex.com,1102 Lagunitas Run,69054,5176 9940 4840 8539,8857
13,Emerson Hatfield,double2010@yandex.com,446 Bartol Bay,73992,3497 877229 27268,15761
14,Marcos Gilmore,occidentalism1859@yahoo.com,1329 Argonaut Esplanade,24929,4244 6172 4853 1393,5057
15,Malik Velez,siamese1936@outlook.com,925 Eastwood Stravenue,9986,3703 456661 72094,21045
16,Estell Mcknight,nonswimming1985@yahoo.com,814 Tompkins Plaza,20396,4891 5856 8926 8179,7078
17,Lilla Navarro,dockyards2058@yahoo.com,570 Peek Trace,15667,5208 9153 9009 0544,12993
18,Kallie Mcfarland,paucity1995@yahoo.com,585 Dock Field,76244,4819 6292 6429 1302,15658
19,Isiah Alexander,pouncing1910@live.com,571 Roscoe Gate,52510,3497 195524 75118,15901
20,Ronny Bowen,heft1945@live.com,1156 Fenton Close,17749,3408 704958 51110,13265
21,Chauncey Robles,charmian1906@yandex.com,1060 Candlestick Cove Path,26597,5476 2170 9722 0523,12801
22,Travis Dalton,curate1853@gmail.com,1072 Franklin Gate,63820,3750 913352 55002,18096
23,Lane Holden,concentrate1983@live.com,197 Alana Plantation,25141,4482 7479 4361 7998,20469
24,Flavia Robertson,exceptionalness2044@live.com,264 Head Crescent,64162,4752 2321 7533 0753,19976
25,Roy Leblanc,bijou1921@live.com,124 Lake Merced Hill Drive,1027,3788 345883 52472,12517
26,Phebe Miranda,euda1886@yahoo.com,1019 Langdon Boulevard,37828,4267 4742 5832 2608,15826
27,Annis Cummings,batteries2003@outlook.com,624 Dorado Loop,83529,5265 1780 9504 7042,20013
28,Jamaal Bradley,shivarees1849@live.com,873 Hiliritas Concession road,2412,3725 893950 26000,12304
29,Patrick Bishop,cappadine1872@outlook.com,1353 Wilson Grove,62899,3797 755867 73491,24207
...,...,...,...,...,...,...
70,Darrin Bartlett,mayfly1903@yandex.com,296 Ruth Pike,86306,3407 365350 63646,7955
71,Bret Butler,beylic1844@outlook.com,182 Randolph Plantation,67960,4310 3140 6783 0069,18829
72,Ja Craft,finch2041@outlook.com,574 Roach Alley,70810,4850 0893 0677 8610,9839
73,Bryant Mcknight,annoyed2054@live.com,15 Felton Row,26854,3475 838319 26438,23892
74,Gwenda Haley,apolline1844@outlook.com,1129 Palo Alto Place,80135,4479 7058 3301 7948,21763
75,Rosendo Mercado,ashton1830@gmail.com,930 Ironwood Path,19211,2428 3964 8941 1787,18389
76,Derrick Delacruz,dovelet1813@live.com,537 Harding Avenue,87814,3745 952844 94538,16394
77,Daryl Wong,rivals1832@gmail.com,638 Augusta Crescent,95436,3773 439333 72137,12640
78,Kent Wade,porpoise1827@live.com,580 Serrano Manor,447,3775 015326 21937,11674
79,Ciera Sellers,nonanarchic2041@gmail.com,725 Barneveld Manor,46005,3405 060086 70254,24326
80,Terrell Ramsey,consciousness1931@outlook.com,1133 Costa Alley,43825,5408 2428 3615 4406,21289
81,Olinda Stokes,byproducts1960@yahoo.com,1217 Hutchins Ferry,76135,4727 0327 8246 9701,9190
82,Odis Blackwell,amines1975@gmail.com,380 York Avenue,16354,3412 163043 95494,16006
83,Fernanda Mccarty,cousins1924@gmail.com,617 Commercial Extension,72082,3762 346268 76917,3377
84,Johnny Foster,poephaga1853@live.com,59 Dukes Promenade,62635,5262 6825 3034 2333,13825
85,Herschel Mcgee,eller1996@gmail.com,86 Miller Side road,20605,3445 781140 96050,1131
86,Renay Hart,peddles2025@live.com,791 Troy Townline,42969,2613 0358 1800 8493,18895
87,Elsy Dudley,posadaship2026@live.com,295 Grafton Green,87181,4110 3221 7388 8865,3278
88,Allen Newman,exciton1867@live.com,704 Bigelow Stravenue,9252,4296 2923 7047 3702,15768
89,Katlyn Sparks,detur2023@yahoo.com,1259 Dellbrook Expressway,22658,5548 0512 5986 4743,18561
90,Chang Brewer,untightened1949@gmail.com,553 Bennington Promenade,54615,3461 529538 56582,20836
91,Daren Haley,concrete1909@outlook.com,1201 Mint Wynd,62859,3706 624226 90486,19002
92,Delmer Beck,demandative1829@yahoo.com,1168 Southard Brae,67885,2442 6485 8353 1676,24540
93,Tobias Pearson,arlin2068@gmail.com,1301 Melba Promenade,26050,3478 459127 82794,18707
94,Ayesha Weiss,malarkeys1970@yahoo.com,267 White Trace,4542,5582 5048 5381 8264,17977
95,Crystle Larson,plantula1818@live.com,1317 Cesar Chavez On Brae,74413,3474 949615 85541,5091
96,Jetta Davenport,doolittle1818@yandex.com,618 Williams Terrace,73152,4711 5533 4972 2249,16509
97,Dallas Johnston,mosso1961@live.com,324 Tenny Line,88215,3794 280688 77410,24196
98,Roberto Daugherty,ovenful1914@yandex.com,1058 Marengo Manor,33903,4972 5355 6633 9108,18828
99,Abel Walters,esson1909@yandex.com,89 Rivera Bypass,39186,3727 728484 48704,3400

In [15]:
customer_dataframe["Balance_thousands"] = customer_dataframe["Balance"]/1000

In [16]:
customer_dataframe.head()

,full_name,Email,Address,zip_code,CreditCard,Balance,Balance_thousands
0,Altha Frederick,unhideable1966@gmail.com,67 John Maher Extension,31353,2524 2317 2139 4751,21511,21.511
1,Nickolas Harvey,allgood1803@outlook.com,1200 Madera Plaza,1922,4756 0997 9568 1329,13850,13.850
2,Jesusita Kinney,satsumas1954@yahoo.com,943 Gibb Highway,41535,3717 863466 48574,21254,21.254
3,Mose Gordon,antifowl1875@gmail.com,1073 Fell Trace,16098,5413 1700 6989 2835,5221,5.221
4,Cesar Valentine,acetaminol1979@yahoo.com,805 Marshall Promenade,99895,5173 4883 9215 4743,8300,8.300

In [17]:
customer_dataframe["full_name"]

0         Altha Frederick
1         Nickolas Harvey
2         Jesusita Kinney
3             Mose Gordon
4         Cesar Valentine
5            Erich Wooten
6             Elias Ayers
7         Boris Macdonald
8             Emilio Bird
9          Vincenza Patel
10       Norberto Pollard
11    Kristeen Hutchinson
12       Jestine Mcdowell
13       Emerson Hatfield
14         Marcos Gilmore
15            Malik Velez
16        Estell Mcknight
17          Lilla Navarro
18       Kallie Mcfarland
19        Isiah Alexander
20            Ronny Bowen
21        Chauncey Robles
22          Travis Dalton
23            Lane Holden
24       Flavia Robertson
25            Roy Leblanc
26          Phebe Miranda
27         Annis Cummings
28         Jamaal Bradley
29         Patrick Bishop
             ...
70        Darrin Bartlett
71            Bret Butler
72               Ja Craft
73        Bryant Mcknight
74           Gwenda Haley
75        Rosendo Mercado
76       Derrick Delacruz
77             Daryl Wong
78              Kent Wade
79          Ciera Sellers
80         Terrell Ramsey
81          Olinda Stokes
82         Odis Blackwell
83       Fernanda Mccarty
84          Johnny Foster
85         Herschel Mcgee
86             Renay Hart
87            Elsy Dudley
88           Allen Newman
89          Katlyn Sparks
90           Chang Brewer
91            Daren Haley
92            Delmer Beck
93         Tobias Pearson
94           Ayesha Weiss
95         Crystle Larson
96        Jetta Davenport
97        Dallas Johnston
98      Roberto Daugherty
99           Abel Walters
Name: full_name, Length: 100, dtype: object

In [20]:
names = customer_dataframe["full_name"].str.split(" ", expand=True)

In [21]:
customer_dataframe["first_name"] = names[0]
customer_dataframe["last_name"] = names[1]
customer_dataframe.head()

,full_name,Email,Address,zip_code,CreditCard,Balance,Balance_thousands,first_name,last_name
0,Altha Frederick,unhideable1966@gmail.com,67 John Maher Extension,31353,2524 2317 2139 4751,21511,21.511,Altha,Frederick
1,Nickolas Harvey,allgood1803@outlook.com,1200 Madera Plaza,1922,4756 0997 9568 1329,13850,13.850,Nickolas,Harvey
2,Jesusita Kinney,satsumas1954@yahoo.com,943 Gibb Highway,41535,3717 863466 48574,21254,21.254,Jesusita,Kinney
3,Mose Gordon,antifowl1875@gmail.com,1073 Fell Trace,16098,5413 1700 6989 2835,5221,5.221,Mose,Gordon
4,Cesar Valentine,acetaminol1979@yahoo.com,805 Marshall Promenade,99895,5173 4883 9215 4743,8300,8.300,Cesar,Valentine

In [24]:
customer_dataframe = customer_dataframe.drop(columns=["full_name"])

In [25]:
customer_dataframe.head()

,Email,Address,zip_code,CreditCard,Balance,Balance_thousands,first_name,last_name
0,unhideable1966@gmail.com,67 John Maher Extension,31353,2524 2317 2139 4751,21511,21.511,Altha,Frederick
1,allgood1803@outlook.com,1200 Madera Plaza,1922,4756 0997 9568 1329,13850,13.850,Nickolas,Harvey
2,satsumas1954@yahoo.com,943 Gibb Highway,41535,3717 863466 48574,21254,21.254,Jesusita,Kinney
3,antifowl1875@gmail.com,1073 Fell Trace,16098,5413 1700 6989 2835,5221,5.221,Mose,Gordon
4,acetaminol1979@yahoo.com,805 Marshall Promenade,99895,5173 4883 9215 4743,8300,8.300,Cesar,Valentine